export default function appoint(task: string) {
    return task == 'login'
        ? 'Login'
        : task == 'save'
            ? 'Save this file'
            : task == 'content'
                ? 'Insert content'
                : task == 'function'
                    ? 'Insert a function'
                    : task == 'script'
                        ? 'Insert a script'
                        : task == 'chart'
                            ? 'Chart visualisations'
                            : 'Styles properties'
}