export default function render(index: number, task: string) {
    return !index
        ? task === 'login'
            || task === 'save'
            || task === 'script'
            ? 'text'
            : task === 'data'
                ? 'file'
                : task == 'function'
                    ? 'number'
                    : task == 'style'
                        ? 'color'
                        : 'hidden'
        : task === 'login'
            ? 'password'
            : task == 'function'
                ? 'number'
                : task == 'style'
                    ? 'range'
                    : task === 'save'
                        || task === 'data'
                        || task === 'chart'
                        || task === 'script'
                        ? 'hidden'
                        : ''
}