export default function label(index: 0 | 1, task: string) {
    return index == 0
        ? task == 'login'
            ? 'Username'
            : task == 'save'
                ? 'Name'
                : task == 'data'
                    ? 'File'
                    : task == 'function'
                        ? '1st parameter'
                        : task == 'script'
                            ? 'Script'
                            : 'Color'
        : task == 'login'
            ? 'Password'
            : task == 'function'
                ? '2nd parameter'
                : task == 'scripts'
                    ? 'Console'
                    : task == 'style'
                        ? 'Size'
                        : 'Value'
}